In [1]:
import torch

In [4]:
def print_val(x):
    print "Type:", type(x)
    print "Shape:", x.shape
    print "값:\n", x
    print " "

In [5]:
x = torch.rand(2,3,2) # uniform 0~1 사이 모든 값들이 나올 확률이 같음
print_val(x)

x = torch.randn(2,3) # Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3, 2])
값:
tensor([[[0.8018, 0.4229],
         [0.1534, 0.0213],
         [0.2429, 0.9586]],

        [[0.6039, 0.7750],
         [0.3191, 0.9378],
         [0.9648, 0.6309]]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[ 0.1745,  1.0494, -0.9304],
        [ 1.6985, -1.4786, -0.2299]])
 


In [6]:
x = torch.randperm(4) # 0 ~ n-1 까지 값을 원소로 갖는 배열 -> 랜덤 배열
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([4])
값:
tensor([3, 1, 2, 0])
 


In [7]:
# [start, end] 구간을 step 단위로 나눠서 배열로 생성
x = torch.arange(0, 3, step=0.5)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([6])
값:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
 


In [8]:
print_val( torch.ones(3,4) )
print_val( torch.zeros(3,4) )

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
 


In [9]:
print_val( torch.Tensor(2,4) )

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 4])
값:
tensor([[ 3.8399e+01,  4.5612e-41,  3.8399e+01,  4.5612e-41],
        [-3.7331e-26,  3.0840e-41,  2.6804e+01,  4.5612e-41]])
 


In [10]:
print_val( torch.Tensor([2,3]) )

print_val( torch.Tensor([[2,3], [3,4]]) )

Type: <class 'torch.Tensor'>
Shape: torch.Size([2])
값:
tensor([2., 3.])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
값:
tensor([[2., 3.],
        [3., 4.]])
 


In [11]:
# 텐서 타입 변환
x = torch.FloatTensor(2,3)
print_val(x)

x = x.type_as(torch.IntTensor())
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[3.8399e+01, 4.5612e-41, 3.8399e+01],
        [4.5612e-41, 0.0000e+00, 0.0000e+00]])
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[38,  0, 38],
        [ 0,  0,  0]], dtype=torch.int32)
 


In [12]:
# 텐서 크기 변환
torch. FloatTensor(3,4,5).size()

torch.Size([3, 4, 5])

In [13]:
# numpy array -> torch tensor
import numpy as np
np_x = np.ndarray((2,3), dtype=int)
print_val(np_x)

x = torch.from_numpy(np_x)
print_val(x)

Type: <type 'numpy.ndarray'>
Shape: (2, 3)
값:
[[139802294458472 139802294458472 139800169664656]
 [    25769803782     25769803782     25769803782]]
 
Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값:
tensor([[139802294458472, 139802294458472, 139800169664656],
        [    25769803782,     25769803782,     25769803782]])
 
